import { Application } from 'express';
import userRoute from './user.route';
import authRoute from './auth.route';
import categoryRoute from './category.route';
import brandRoute from './brand.route';
import productRoute from './product.route';
import unitRoute from './unit.route';
import imageRoute from './image.route';
import unitTypeRoute from './unit-type.route';
import serviceRoute from './service.route';
import taxTypeRoute from './tax-type.route';
import taxRoute from './tax.route';
import personGroupTypeRoute from './person-group-type.route';
import debtTypeRoute from './debt-type.route';
import statusTypeRoute from './status-type.route';
import statusRoute from './status.route';
import paymentMethodRoute from './payment-method.route';
import comboRoute from './combo.route';
import provinceRoute from './province.route';
import districtRoute from './district.route';
import wardRoute from './ward.route';
import supplierGroupRoute from './supplier-group.route';
import supplierRoute from './supplier.route';
import comboItemRoute from './combo-item.route';
import voucherTypeRoute from './voucher-type.route';
import voucherGroupTypesRoute from './voucher-group-types.route';
import voucherGroupRoute from './voucher-group.route';
import voucherRoute from './voucher.route';
import purchaseOrderRoute from './purchase-order.route';
import purchaseOrderPaymentRoute from './purchase-order-payment.route';
import customerRoute from './customer.route';
import returnedPurchaseOrderRoute from './returned-purchase-order.route';
import lossReasonRoute from './loss-reason.route';
import orderSupplierRoute from './orderSupplier.route';
import stockAdjustmentRoute from './stock-adjustment.route';
import customerGroupRoute from './customer-group.route';
import deliveryPartnerGroupRoute from './delivery-partner-group.route';
import deliveryMethodRoute from './delivery-method.route';
import deliveryPartnerRoute from './delivery-partner.route';
import orderRoute from './order.route';
import orderPaymentRoute from './order-payment.route';
import statisticRoute from './statistic.route';
import exportPdfRoute from './export-pdf.route';
import productUnitRoute from './product-unit.route';
import sizeUnitRoute from './size-unit.route';
import specificationTypeRoute from './specification-type.route';
import specificationRoute from './specification.route';
import returnOrderRoute from './returned-order.route';


export default class Routes {
  constructor(app: Application) {
    app.use('/api/auth', authRoute);
    app.use('/api/users', userRoute);
    app.use('/api/categories', categoryRoute);
    app.use('/api/brands', brandRoute);
    app.use('/api/unit-types', unitTypeRoute);
    app.use('/api/units', unitRoute);
    app.use('/api/products', productRoute);
    app.use('/api/images', imageRoute);
    app.use('/api/services', serviceRoute);
    app.use('/api/tax-types', taxTypeRoute);
    app.use('/api/taxes', taxRoute);
    app.use('/api/person-group-types', personGroupTypeRoute);
    app.use('/api/debt-types', debtTypeRoute);
    app.use('/api/status-types', statusTypeRoute);
    app.use('/api/statuses', statusRoute);
    app.use('/api/payment-methods', paymentMethodRoute);
    app.use('/api/combos', comboRoute);
    app.use('/api/combo-items', comboItemRoute);
    app.use('/api/provinces', provinceRoute);
    app.use('/api/districts', districtRoute);
    app.use('/api/wards', wardRoute);
    app.use('/api/supplier-groups', supplierGroupRoute);
    app.use('/api/suppliers', supplierRoute);
    app.use('/api/voucher-types', voucherTypeRoute);
    app.use('/api/voucher-group-types', voucherGroupTypesRoute);
    app.use('/api/voucher-groups', voucherGroupRoute);
    app.use('/api/vouchers', voucherRoute);
    app.use('/api/purchase-orders', purchaseOrderRoute);
    app.use('/api/purchase-order-payments', purchaseOrderPaymentRoute);
    app.use('/api/customers', customerRoute);
    app.use('/api/returned-purchase-orders', returnedPurchaseOrderRoute);
    app.use('/api/loss-reasons', lossReasonRoute);
    app.use('/api/order-suppliers', orderSupplierRoute);
    app.use('/api/stock-adjustments', stockAdjustmentRoute);
    app.use('/api/customer-groups', customerGroupRoute);
    app.use('/api/delivery-partner-groups', deliveryPartnerGroupRoute);
    app.use('/api/delivery-methods', deliveryMethodRoute);
    app.use('/api/delivery-partners', deliveryPartnerRoute);
    app.use('/api/orders', orderRoute);
    app.use('/api/order-payments', orderPaymentRoute);
    app.use('/api/statistics', statisticRoute);
    app.use('/api/pdf-export', exportPdfRoute);
    app.use('/api/product-units', productUnitRoute);
    app.use('/api/size-units', sizeUnitRoute);
    app.use('/api/specification-types', specificationTypeRoute);
    app.use('/api/specifications', specificationRoute);
    app.use('/api/returned-orders', returnOrderRoute);
  }
}
